Repository MrCroxx/RunKV, pull requests merged in 2022-05, with the labels that each got.

#123 feat: enable/disable metrics with env
  Makefile
  wheel/src/lib.rs
Labels: feature

#121 feat: replace openraft with async version raft-rs
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/log.rs
  common/src/tracing_slog_drain.rs
  proto/src/proto/wheel.proto
  rust-toolchain
  storage/src/error.rs
  storage/src/lib.rs
  storage/src/lsm_tree/components/block.rs
  storage/src/raft_log_store_v2/block_cache.rs
  storage/src/raft_log_store_v2/entry.rs
  storage/src/raft_log_store_v2/error.rs
  storage/src/raft_log_store_v2/log.rs
  storage/src/raft_log_store_v2/mem.rs
  storage/src/raft_log_store_v2/mod.rs
  storage/src/raft_log_store_v2/store.rs
  tests/integrations/mod.rs
  wheel/Cargo.toml
  wheel/src/components/fsm_v2.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/mod.rs
  wheel/src/components/network.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_log_store_v2.rs
  wheel/src/components/raft_manager_v2.rs
  wheel/src/components/raft_network.rs
  wheel/src/error.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/service_v2.rs
  wheel/src/worker/heartbeater.rs
  wheel/src/worker/kv.rs
  wheel/src/worker/mod.rs
  wheel/src/worker/raft.rs
  wheel/src/worker/sstable_uploader.rs
Labels: enhancement

#125 refactor: remove openraft deps, rename all v2 modules
  Cargo.lock
  storage/src/error.rs
  storage/src/lib.rs
  storage/src/raft_log_store/block_cache.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/store.rs
  storage/src/raft_log_store_v2/block_cache.rs
  storage/src/raft_log_store_v2/entry.rs
  storage/src/raft_log_store_v2/error.rs
  storage/src/raft_log_store_v2/log.rs
  storage/src/raft_log_store_v2/mem.rs
  storage/src/raft_log_store_v2/mod.rs
  storage/src/raft_log_store_v2/store.rs
  wheel/Cargo.toml
  wheel/src/components/fsm.rs
  wheel/src/components/fsm_v2.rs
  wheel/src/components/gear.rs
  wheel/src/components/mod.rs
  wheel/src/components/network.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_log_store_v2.rs
  wheel/src/components/raft_manager.rs
  wheel/src/components/raft_manager_v2.rs
  wheel/src/error.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/service_v2.rs
  wheel/src/worker/kv.rs
  wheel/src/worker/mod.rs
  wheel/src/worker/raft.rs
Labels: refactor

#127 fix: fix cargo make scripts
  Makefile.toml
  etc/prometheus.yml
  make/grafana.toml
  make/prometheus.toml
  tests/integrations/mod.rs
Labels: bug

#128 feat: use tracing feature to reduce operations for tracing
  Cargo.lock
  common/Cargo.toml
  common/src/coding.rs
  common/src/context.rs
  common/src/lib.rs
  common/src/log.rs
  proto/Cargo.toml
  proto/src/lib.rs
  tests/Cargo.toml
  tests/integrations/mod.rs
  wheel/Cargo.toml
  wheel/src/components/command.rs
  wheel/src/components/fsm.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: enhancement, feature

#129 test: test multi raft groups
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/store.rs
  tests/integrations/mod.rs
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: test

#130 test: enable both multi-group and single-group test
  Cargo.lock
  tests/Cargo.toml
  tests/etc/exhauster.toml
  tests/etc/port.toml
  tests/etc/rudder.toml
  tests/etc/wheel.toml
  tests/integrations/lib.rs
  tests/integrations/test_concurrent_put_get.rs
  tests/integrations/test_multi_raft_group_concurrent_put_get.rs
Labels: test

#131 feat: add grafana support as metrics service
  Makefile.toml
  etc/grafana-dashboards/runkv-overview.json
  etc/grafana-provisioning/dashboards/runkv-dashboards.yml
  etc/grafana-provisioning/datasources/runkv-prometheus.yml
  etc/grafana.ini
  make/common.toml
  make/grafana.toml
  make/prometheus.toml
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: feature

#132 bench: introduce raft log store benchmark
  Cargo.lock
  storage/Cargo.toml
  storage/bench/bench_raft_log_store.rs
Labels: test

#133 feat: replace rate with irate in metrics and intrduce more metrics
  etc/grafana-dashboards/runkv-overview.json
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: bug, feature

#134 feat: using client-side streaming and avoiding read lock to optimize raft message sending
  Cargo.lock
  Cargo.toml
  client/Cargo.toml
  client/src/lib.rs
  etc/grafana-dashboards/runkv-overview.json
  proto/src/proto/wheel.proto
  tests/Cargo.toml
  wheel/Cargo.toml
  wheel/src/components/raft_network.rs
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: enhancement, feature

#136 feat: introduce raft log store metrics skeleton
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/prometheus.rs
  etc/grafana-dashboards/runkv-overview.json
  storage/Cargo.toml
  storage/bench/bench_raft_log_store.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/metrics.rs
  storage/src/raft_log_store/mod.rs
  storage/src/raft_log_store/store.rs
  wheel/Cargo.toml
  wheel/src/components/raft_log_store.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: feature

#138 feat: batching raft log entries appends for raft log store, fix propose out-of-order sequences
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/sync.rs
  etc/grafana-dashboards/runkv-overview.json
  storage/bench/bench_raft_log_store.rs
  storage/src/error.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/metrics.rs
  storage/src/raft_log_store/store.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/service.rs
Labels: bug, enhancement, feature

#140 feat: send raft message vec in one request
  etc/grafana-dashboards/runkv-overview.json
  proto/src/proto/wheel.proto
  wheel/src/components/raft_network.rs
  wheel/src/service.rs
Labels: feature

#141 refactor: refactor some metrics field name and display
  etc/grafana-dashboards/runkv-overview.json
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: refactor

#143 feat: raft log store append raft log batch vec
  etc/grafana-dashboards/runkv-overview.json
  storage/bench/bench_raft_log_store.rs
  storage/src/raft_log_store/block_cache.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/metrics.rs
  storage/src/raft_log_store/store.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_manager.rs
  wheel/src/worker/raft.rs
Labels: feature

#144 feat: reduce write file rate when append log
  .gitignore
  etc/grafana-dashboards/runkv-overview.json
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/metrics.rs
Labels: feature

#147 fix: heartbeat raise error if no version diff
  Cargo.lock
  common/Cargo.toml
  common/src/log.rs
  etc/grafana-dashboards/runkv-overview.json
  etc/wheel.toml
  rudder/src/lib.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/store.rs
  tests/etc/wheel.toml
  tests/integrations/test_concurrent_put_get.rs
  tests/integrations/test_multi_raft_group_concurrent_put_get.rs
  wheel/src/config.rs
  wheel/src/service.rs
  wheel/src/worker/heartbeater.rs
  wheel/src/worker/raft.rs
Labels: bug, feature

#148 fix: fix key generation rule in integration test
  tests/integrations/test_concurrent_put_get.rs
  tests/integrations/test_multi_raft_group_concurrent_put_get.rs
Labels: bug

#151 feat: introduce sharded hash map
  Cargo.lock
  common/Cargo.toml
  common/benches/bench_sharded_hash_map.rs
  common/src/lib.rs
  common/src/sharded_hash_map.rs
Labels: feature

#146 feat: lsm tree block cache metrics
  etc/grafana-dashboards/runkv-overview.json
  exhauster/src/lib.rs
  rudder/src/lib.rs
  storage/src/lsm_tree/components/block_cache.rs
  storage/src/lsm_tree/components/metrics.rs
  storage/src/lsm_tree/components/mod.rs
  storage/src/lsm_tree/components/sstable_store.rs
  storage/src/lsm_tree/iterator/sstable_iterator.rs
  storage/src/lsm_tree/iterator/user_key_iterator.rs
  storage/src/lsm_tree/manifest/version.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
Labels: feature

#153 feat: introduce Packer for batching
  Cargo.lock
  bench/Cargo.toml
  bench/bench_kv/main.rs
  common/Cargo.toml
  common/src/lib.rs
  common/src/packer.rs
  common/src/sharded_hash_map.rs
  etc/grafana-dashboards/runkv-overview.json
  exhauster/Cargo.toml
  exhauster/src/main.rs
  rudder/Cargo.toml
  rudder/src/main.rs
  wheel/Cargo.toml
  wheel/src/components/fsm.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/raft_manager.rs
  wheel/src/components/raft_network.rs
  wheel/src/lib.rs
  wheel/src/main.rs
  wheel/src/service.rs
  wheel/src/trace.rs
  wheel/src/worker/raft.rs
Labels: feature

#154 feat: add TRACE_CTX for timeline tracing, increase metris precision
  common/src/sharded_hash_map.rs
  etc/grafana-dashboards/runkv-overview.json
  storage/src/lsm_tree/components/metrics.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/metrics.rs
  wheel/src/components/command.rs
  wheel/src/components/fsm.rs
  wheel/src/service.rs
  wheel/src/trace.rs
  wheel/src/worker/raft.rs
Labels: feature

#155 feat: impl ControlService for rudder
  Cargo.lock
  bench/bench_kv/main.rs
  bench/etc/exhauster.toml
  bench/etc/rudder.toml
  bench/etc/wheel.toml
  proto/src/proto/meta.proto
  proto/src/proto/rudder.proto
  proto/src/proto/wheel.proto
  rudder/src/error.rs
  rudder/src/lib.rs
  rudder/src/meta/mem.rs
  rudder/src/meta/mod.rs
  rudder/src/service.rs
  rudder/src/worker/compaction_detector.rs
  tests/integrations/lib.rs
  wheel/Cargo.toml
  wheel/src/components/fsm.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/heartbeater.rs
  wheel/src/worker/raft.rs
Labels: feature

#156 feat: introduce runkv client
  Cargo.lock
  bench/Cargo.toml
  bench/bench_kv/main.rs
  client/Cargo.toml
  client/src/client.rs
  client/src/error.rs
  client/src/lib.rs
  client/src/router.rs
  client/src/worker/heartbeater.rs
  client/src/worker/mod.rs
  proto/src/lib.rs
  proto/src/proto/kv.proto
  proto/src/proto/meta.proto
  proto/src/proto/rudder.proto
  rudder/src/meta/mem.rs
  rudder/src/meta/mod.rs
  rudder/src/service.rs
  wheel/src/components/command.rs
  wheel/src/components/fsm.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/heartbeater.rs
  wheel/src/worker/raft.rs
Labels: feature

#157 feat: support multi wheel bench (on one node)
  bench/bench_kv/main.rs
  bench/etc/wheel.toml
  etc/prometheus.yml
  storage/src/raft_log_store/metrics.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/meta/mem.rs
  wheel/src/meta/mod.rs
  wheel/src/service.rs
  wheel/src/worker/heartbeater.rs
  wheel/src/worker/raft.rs
Labels: feature

#158 test: restore integration tests
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Cargo.lock
  bench/Cargo.toml
  bench/bench_kv/main.rs
  tests/Cargo.toml
  tests/integrations/lib.rs
  tests/integrations/test_concurrent_put_get.rs
  tests/integrations/test_multi_raft_group_concurrent_put_get.rs
  tests/src/lib.rs
Labels: test

#163 fix: fix try pin condition, refactor version manager
  exhauster/src/lib.rs
  exhauster/src/service.rs
  rudder/src/lib.rs
  rudder/src/meta/mem.rs
  rudder/src/worker/compaction_detector.rs
  storage/src/lsm_tree/manifest/version.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/lib.rs
  wheel/src/worker/sstable_uploader.rs
Labels: bug, refactor

#166 fix: fix deadlock in runkv_storage::raft_log_store::log
  .gitignore
  Makefile
  bench/Cargo.toml
  common/Cargo.toml
  common/src/log.rs
  common/src/notify_pool.rs
  common/src/packer.rs
  etc/grafana-dashboards/runkv-overview.json
  rudder/src/worker/compaction_detector.rs
  storage/Cargo.toml
  storage/src/lsm_tree/manifest/version.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/store.rs
  wheel/Cargo.toml
  wheel/src/components/fsm.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/service.rs
  wheel/src/worker/raft.rs
Labels: bug

#167 fix: fix raft log store read race
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/file.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/mod.rs
  storage/src/raft_log_store/store.rs
  wheel/src/components/fsm.rs
Labels: bug

#170 feat: introduce LogQueue abstraction to simplify the race condition
  bench/etc/wheel.toml
  storage/src/raft_log_store/error.rs
  storage/src/raft_log_store/file.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/mod.rs
  storage/src/raft_log_store/queue.rs
Labels: feature

#172 feat: introduce aligned buffer for DIO
  Cargo.lock
  storage/Cargo.toml
  storage/src/file_cache/buffer.rs
  storage/src/file_cache/error.rs
  storage/src/file_cache/file.rs
  storage/src/file_cache/mod.rs
  storage/src/lib.rs
  tests/integrations/test_concurrent_put_get.rs
  tests/integrations/test_multi_raft_group_concurrent_put_get.rs
Labels: feature
