Repository MrCroxx/RunKV, pull requests merged in 2022-04, with the labels that each got.

#84 feat: impl raft store log enc dec, adjust dir structure
  Cargo.lock
  storage/Cargo.toml
  storage/src/lib.rs
  storage/src/lsm_tree/components/block.rs
  storage/src/lsm_tree/components/memtable.rs
  storage/src/lsm_tree/components/mod.rs
  storage/src/lsm_tree/components/skiplist/arena.rs
  storage/src/lsm_tree/components/skiplist/key.rs
  storage/src/lsm_tree/components/skiplist/list.rs
  storage/src/lsm_tree/components/skiplist/mod.rs
  storage/src/lsm_tree/components/sstable.rs
  storage/src/lsm_tree/iterator/block_iterator.rs
  storage/src/lsm_tree/iterator/concat_iterator.rs
  storage/src/lsm_tree/iterator/memtable_iterator.rs
  storage/src/lsm_tree/iterator/merge_iterator.rs
  storage/src/lsm_tree/iterator/sstable_iterator.rs
  storage/src/lsm_tree/iterator/user_key_iterator.rs
  storage/src/lsm_tree/mod.rs
  storage/src/raftstore/log.rs
  storage/src/raftstore/mod.rs
  storage/src/utils/bloom.rs
  storage/src/utils/coding.rs
  storage/src/utils/mod.rs
  wheel/Cargo.toml
  wheel/src/storage/lsm_tree.rs
  wheel/src/storage/mod.rs
  wheel/src/storage/raftstore.rs
Labels: feature

#86 fix: compaction pick overlapping sstables by range
  exhauster/src/service.rs
  rudder/src/meta/mem.rs
  rudder/src/worker/compaction_detector.rs
  storage/src/lsm_tree/manifest/version.rs
  wheel/src/storage/lsm_tree.rs
  wheel/src/worker/sstable_uploader.rs
Labels: bug

#87 impl: basic raft log write
  storage/src/error.rs
  storage/src/raftstore/entry.rs
  storage/src/raftstore/log.rs
  storage/src/raftstore/mod.rs
Labels: feature

#90 feat: raft log store (part 2)
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/error.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/mod.rs
  storage/src/raft_log_store/store.rs
Labels: feature

#91 feat: raft log store (part 3)
  Cargo.lock
  storage/Cargo.toml
  storage/src/lib.rs
  storage/src/raft_log_store/block_cache.rs
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/error.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/mod.rs
  storage/src/raft_log_store/store.rs
  wheel/src/storage/raft_log_store.rs
Labels: feature

#94 feat: raft log store (part 4)
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/store.rs
Labels: feature

#97 feat: impl raft log store (part 5)
  Cargo.lock
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/log.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/store.rs
  storage/src/utils/coding.rs
  wheel/Cargo.toml
  wheel/src/error.rs
  wheel/src/storage/mod.rs
  wheel/src/storage/raft_log_store.rs
Labels: feature

#98 feat: raft log store pass openraft test suite
  Cargo.lock
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/store.rs
  wheel/Cargo.toml
  wheel/src/storage/fsm.rs
  wheel/src/storage/mod.rs
  wheel/src/storage/raft_log_store.rs
Labels: feature

#100 feat: support mask for raft log store
  Cargo.lock
  proto/Cargo.toml
  proto/build.rs
  proto/src/proto/wheel.proto
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/mem.rs
  storage/src/raft_log_store/store.rs
  wheel/Cargo.toml
  wheel/src/components/fsm.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/mod.rs
  wheel/src/components/network.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/storage/mod.rs
  wheel/src/worker/sstable_uploader.rs
Labels: feature

#101 feat: introduce async command and gear
  Cargo.lock
  etc/wheel.toml
  tests/Cargo.toml
  tests/etc/wheel.toml
  tests/integrations/mod.rs
  wheel/src/components/command.rs
  wheel/src/components/fsm.rs
  wheel/src/components/mod.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/config.rs
  wheel/src/lib.rs
  wheel/src/service.rs
Labels: feature

#103 feat: raft manager (part1)
  Cargo.lock
  common/src/channel_pool.rs
  wheel/Cargo.toml
  wheel/src/components/gear.rs
  wheel/src/components/network.rs
  wheel/src/components/raft_manager.rs
  wheel/src/error.rs
  wheel/src/lib.rs
  wheel/src/service.rs
Labels: feature

#104 fix: remove async in bench_block_iter.rs fix bugs in bench_block_iter.rs
  storage/Cargo.toml
  storage/benches/bench_block_iter.rs
Labels: bug

#105 feat: separate fsm apply with raft log store
  wheel/src/components/command.rs
  wheel/src/components/fsm.rs
  wheel/src/components/gear.rs
  wheel/src/components/mod.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/service.rs
Labels: feature

#106 feat: gear and kv worker per raft instance
  Cargo.lock
  storage/src/raft_log_store/mod.rs
  storage/src/raft_log_store/store.rs
  wheel/Cargo.toml
  wheel/src/components/command.rs
  wheel/src/components/fsm.rs
  wheel/src/components/gear.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/mod.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
  wheel/src/worker/mod.rs
Labels: feature

#107 feat: fill cache after append raft log
  storage/src/raft_log_store/block_cache.rs
  storage/src/raft_log_store/entry.rs
  storage/src/raft_log_store/store.rs
Labels: enhancement

#108 feat: separate apply and snapshot cmd channel
  storage/src/lsm_tree/mod.rs
  tests/integrations/mod.rs
  wheel/src/components/command.rs
  wheel/src/components/gear.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/raft_manager.rs
  wheel/src/worker/kv.rs
  wheel/src/worker/mod.rs
Labels: feature

#110 feat: impl applier skeleton, revert gear channel separation
  Cargo.lock
  proto/Cargo.toml
  proto/build.rs
  proto/src/lib.rs
  proto/src/proto/kv.proto
  proto/src/proto/wheel.proto
  wheel/src/components/command.rs
  wheel/src/components/gear.rs
  wheel/src/components/raft_manager.rs
  wheel/src/worker/kv.rs
Labels: feature

#111 feat: impl add_endpoints, add_key_range, initialize_raft_group service
  proto/src/proto/wheel.proto
  tests/integrations/mod.rs
  wheel/src/components/raft_manager.rs
  wheel/src/error.rs
  wheel/src/meta/mem.rs
  wheel/src/meta/mod.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
Labels: feature

#112 fix: fix raft log block cache indexing
  storage/src/raft_log_store/store.rs
  tests/integrations/mod.rs
  wheel/src/components/network.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
  wheel/src/worker/mod.rs
Labels: bug

#113 feat: impl notify pool
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/notify_pool.rs
  proto/src/lib.rs
  wheel/src/components/command.rs
  wheel/src/components/gear.rs
  wheel/src/components/raft_log_store.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
Labels: feature

#115 feat: notify after apply with notify pool
  common/src/notify_pool.rs
  wheel/src/components/command.rs
  wheel/src/components/raft_manager.rs
  wheel/src/error.rs
  wheel/src/lib.rs
  wheel/src/meta/mem.rs
  wheel/src/meta/mod.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
Labels: feature

#116 feat: impl memtable per shard (part 1)
  exhauster/src/compaction_filter.rs
  exhauster/src/partitioner.rs
  exhauster/src/service.rs
  rudder/src/service.rs
  storage/src/lsm_tree/components/memtable.rs
  storage/src/lsm_tree/components/sstable.rs
  storage/src/lsm_tree/iterator/memtable_iterator.rs
  storage/src/lsm_tree/iterator/user_key_iterator.rs
  storage/src/lsm_tree/manifest/version.rs
  storage/src/utils/coding.rs
  tests/integrations/mod.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/raft_manager.rs
  wheel/src/lib.rs
  wheel/src/main.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
  wheel/src/worker/sstable_uploader.rs
Labels: feature, refactor

#117 feat: bind raft and lsm-tree together!
  Cargo.lock
  common/Cargo.toml
  common/src/lib.rs
  common/src/time.rs
  proto/src/proto/kv.proto
  tests/integrations/mod.rs
  wheel/src/components/command.rs
  wheel/src/components/lsm_tree.rs
  wheel/src/components/raft_manager.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
Labels: feature

#119 feat: introduce jaeger support for tracing
  Cargo.lock
  Makefile.toml
  common/Cargo.toml
  common/src/lib.rs
  common/src/log.rs
  common/src/time.rs
  exhauster/Cargo.toml
  make/jaeger.toml
  rudder/Cargo.toml
  tests/Cargo.toml
  tests/integrations/mod.rs
  wheel/Cargo.toml
  wheel/src/components/raft_log_store.rs
  wheel/src/service.rs
  wheel/src/worker/kv.rs
Labels: feature

#120 feat: control enable/disable tracing with env
  Cargo.toml
  common/src/log.rs
  tests/integrations/mod.rs
Labels: feature

#122 feat: introduce prometheus and grafana as metrics service
  Cargo.lock
  Makefile.toml
  common/src/config.rs
  make/grafana.toml
  make/prometheus.toml
  tests/etc/prometheus.yml
  tests/etc/wheel.toml
  wheel/Cargo.toml
  wheel/src/config.rs
  wheel/src/lib.rs
  wheel/src/service.rs
Labels: feature
